### ISSUE TITLE
Query definition in the glossary

### ISSUE THREAD

**Issue by orchid00** [swcarpentry/sql-novice-survey#104]
The query definition is not consistent with what is said on the creating and modifying data

Records can be inserted, updated, or deleted using "queries".
Whereas query definition says: A database operation that reads values but does not modify anything.

I think queries not only retrieve information, but Insert, Update, Drop statements can also be called queries?
Either one of those two should be fixed.

**Comment by gvwilson** [comment]
Fixed in bae9fe2
