### ISSUE TITLE
showing null values

### ISSUE THREAD

**Issue by orchid00** [swcarpentry/sql-novice-survey#105]
Why are null values shown as -null- on some tables?
if we do SELECT * FROM Table; it shows empty rows. Examples should show empty rows as well. There's inconsistencies in the way null values are shown, across the lessons in sql-novice

shown as -null-
http://swcarpentry.github.io/sql-novice-survey/01-select.html
http://swcarpentry.github.io/sql-novice-survey/02-sort-dup.html
http://swcarpentry.github.io/sql-novice-survey/05-null.html
http://swcarpentry.github.io/sql-novice-survey/06-agg.html
http://swcarpentry.github.io/sql-novice-survey/07-join.html
http://swcarpentry.github.io/sql-novice-survey/08-hygiene.html

shown as empty cell
http://swcarpentry.github.io/sql-novice-survey/03-filter.html

**Comment by acabunoc** [comment]
Thanks @orchid00 -- yes I believe we should be consistent across the lessons.

I think we can open up the discussion on what -null- representation we should use. I can see arguments for either side.

Shown as -null-:
Teach the terminology.

Shown as empty:
Probably a better representation of what's actually there.

**Comment by raquel-ucl** [comment]
Hiya. I was wondering if I could work on this and make these null values consistent in the lesson's materials. My opinion is it's better to show them as empty, since students are using sqlite3 in their terminals and that's how they appear in the screen. Then you can explain in the text that they are empty because they are null. I'll make a pull request with these changes and wait for your comments :)

**Comment by raquel-ucl** [comment]
I have forked this repository and tried to `make check` the `gh-pages` branch and run into this problem:

```
make check
python tools/check.py .
Traceback (most recent call last):
  File "tools/check.py", line 846, in <module>
    main(parsed_args)
  File "tools/check.py", line 831, in main
    res = validate_single(fn, template=template)
  File "tools/check.py", line 711, in validate_single
    validate_file = validator(filepath)
  File "tools/check.py", line 80, in __init__
    ast = self._parse_markdown(self.markdown)
  File "tools/check.py", line 87, in _parse_markdown
    parser = CommonMark.DocParser()
AttributeError: 'module' object has no attribute 'DocParser'
make: *** [check] Error 1
```

I'm not sure how to tackle this. Sorry, this is my first contribution to the SWC lessons :)

**Comment by acabunoc** [comment]
Hey @raquel-ucl! Thanks so much for looking into this!

Searched a bit and it looks like you're not the first person to run into this problem :)
https://github.com/swcarpentry/lesson-example/issues/19

This line will probably help:
`You should consider upgrading via the 'pip install --upgrade pip' command.`

Let me know if you need any help! If you could updates just the .md files (and the .html ones), that would be very helpful!

**Comment by acabunoc** [comment]
Actually, this is probably the useful line:
`pip install --upgrade CommonMark==0.5.5`

**Comment by raquel-ucl** [comment]
Yes, that works! Thanks for the help.  I'll see if I can make a preview of the repo as is just to check I'm able to check my changes :)

**Comment by acabunoc** [comment]
Have fun @raquel-ucl - let me know if you have any questions :)
