### ISSUE TITLE
Programing with databases in R

### ISSUE THREAD

**Issue by orchid00** [swcarpentry/sql-novice-survey#106]
Is it possible to mention that databases can be used from R as well as in the python example in lesson 10?
the function sqldf() in R works perfect for database queries and I think should be at least mentioned somewhere in this page.

**Comment by rgaiacs** [comment]
> Is it possible to mention that databases can be used from R as well as in the python example in lesson 10?

+1.

**Comment by acabunoc** [comment]
+1

**Comment by rachelss** [comment]
Yes, please add the R version of programming databases

**Comment by gvwilson** [comment]
Would someone who speaks R like to add something to `_episodes/10-prog.md` showing how to connect and extract data in R?

**Comment by jstaf** [comment]
Added some R lesson materials, see https://github.com/swcarpentry/sql-novice-survey/pull/143
