### ISSUE TITLE
SQLite database not available

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/sql-novice-survey#111]
~~~
$ find . -name '*.db'
$ find . -name '*.sql'
./code/gen-survey-database.sql
~~~

and

~~~
$ ls -1 data
person.csv
site.csv
survey.csv
visited.csv
~~~

**Comment by njamescouk** [comment]
save the following as sqlite.input in same dir as CSV files. apologies for lack of pull request, I'm a total noob here, will get to the git lesson in due course.
file begins on line below:

-- strictly speaking not sql as we use sqlite3 . commands
-- use with command line `sqlite3 survey1.db < sqlite.input`
-- I've renamed fields with a rational scheme plus added 
-- foreign key constraints
-- replace create table stmts below with ones from original 
-- survey.db (via .schema) and you'll recreate the original
-- survey.db as opposed to this one
-- NULL fields are treated differently to original survey.db
-- do `sqlite3 survey.db ".dump" > dump.sql & sqlite3 survey1.db ".dump" > dump1.sql & diff dump.sql dump1.sql`
-- to see changes 

DROP TABLE IF EXISTS Person;
DROP TABLE IF EXISTS Site;
DROP TABLE IF EXISTS Visited;
DROP TABLE IF EXISTS Survey;

CREATE TABLE Person
(
    id TEXT PRIMARY KEY,
    personal TEXT,
    family TEXT
);
CREATE TABLE Site
(
    id TEXT PRIMARY KEY,
    lat REAL,
    long REAL
);
CREATE TABLE Visited
(
    id INTEGER PRIMARY KEY,
    siteId TEXT,
    dated DATE,
    FOREIGN KEY (siteId) REFERENCES Site(ID)
);
CREATE TABLE Survey
(
    visitedId INTEGER,
    personId TEXT,
    quant TEXT,
    reading REAL,
    FOREIGN KEY (visitedId) REFERENCES Visited(ID),
    FOREIGN KEY (personId) REFERENCES Person(ID)
);

.mode csv
.import person.csv Person
.import site.csv Site
.import survey.csv Survey
.import visited.csv Visited

**Comment by njamescouk** [comment]
picture of db (with my field names) at https://db.tt/m1jHeNzr

**Comment by njamescouk** [comment]
however renaming fields involves rewriting the lessons...

**Comment by gvwilson** [comment]
I believe this has now been addressed.
