### ISSUE TITLE
SQLite installation issue on Windows

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/sql-novice-survey#118]
From one workshop

> A few windows laptops had an issue with SQLite installation -
> SWC installation package (which includes nano, sqlite etc) didn't works because learners have
> no permission to install, and single file binary from SQLite website
> didn't do the trick either (for some unknown reason).
> In the end, SQLite manager
> (Firefox plugin) was used as the last resort after 10~15 minutes trying to make SQLite work.

**Comment by njamescouk** [comment]
perhaps copy sqlite3.exe to, say, c:\bin? sqlite3 DLL dependencies are in system32 so no worries with that. path and file associations could be a pain though.

**Comment by wking** [comment]
Superseded by swcarpentry/windows-installer#43?

**Comment by gvwilson** [comment]
@embray can this one be closed?

**Comment by lslochov** [comment]
How about using Cygwin for this?

**Comment by remram44** [comment]
> learners have no permission to install

I don't think Cygwin would help with this.

**Comment by lslochov** [comment]
Cygwin can be installed without admin rights using the "--no-admin" flag, and has an sqlite3 package.

https://www.cygwin.com/cygwin-ug-net/setup-net.html

**Comment by henrykironde** [comment]
We have updated instructions for Sqlite installation.
