### ISSUE TITLE
Should we generate the database from a script?

### ISSUE THREAD

**Issue by iglpdc** [swcarpentry/sql-novice-survey#123]
At a workshop today people were confused by the `survey.db` file and I wonder whether it would be better to start off sourcing `survey.sql` instead.

I think what confused people was the fact that the data seemed to appear from nowhere. Maybe a better start should be calling `sqlite3` with no arguments, showing nothing is loaded, and then source `survey.sql` to create the data. 

We could save the file in the next step arguing that a typical database would be much bigger and the process of loading the data much longer.

The advantage that I see is that people could get an idea on which and how the different tables are created (specially instructive for people who are thinking in creating their own database to substitute spreadsheets).

**Comment by iglpdc** [comment]
See also #24 for related discussion about the start.

**Comment by wking** [comment]
On Thu, Jan 14, 2016 at 08:05:50PM -0800, Ivan Gonzalez wrote:
> I think what confused people was the fact that the data seemed to
> appear from nowhere.

I think the current assumption is that most folks will be writing SQL
queries for an existing dataset (e.g. “Welcome to our group!  The past
thirty years of patient data are in SQL at example.com:5432.  Let us
know when you've completed your analysis.”).  For them, it makes sense
to start with “how do you get data out”, and to talk about putting
data in later (time permitting).

> The advantage that I see is that people could get an idea on which
> and how the different tables are created (specially instructive for
> people who are thinking in creating their own database to substitute
> spreadsheets).

Those people are definitely going to be putting data in, and it makes
sense to cater to them too.  I think there may still be an argument
for starting with queries (to motivate *why* you'd want your data in a
database), but I could also see an argument for starting with the
database-creating SQL (to give folks more context before they start
asking questions).  The .schema approach from #24 helps with the
context, but that seems more magical to me than just walking through
gen-survey-database.sql with ‘less’ or a text editor.

Another way to help with context would be to pick simpler data (so
there's less context to absorb).  You'll need at least three tables to
demonstrate JOINs (involving the same table more than once would be
too confusing ;).  Dropping the Visited table (so it's just Person,
Site, and Survey) would make things a bit simpler, while still being
complicated enough to show the benefits of using databases.

**Comment by iglpdc** [comment]
Yes, I wasn't suggesting to write everything on the command line. Maybe simply doing `cat survey.sql` to quickly go thru some of the tables and then:

~~~
$ sqlite3
>>> .read survey.sql
>>> .schema
>>> .save survey.db
>>> .quit
$ ls survey.db
survey.db
~~~

will convince most people that `survey.db` is a binary file that contains the database generated using the SQL commands in `survey.sql`.

**Comment by gvwilson** [comment]
Try it in a couple of workshops, see how it goes, report back?

**Comment by iglpdc** [comment]
Sounds good.

**Comment by acabunoc** [comment]
Anything to report @iglpdc?

**Comment by gvwilson** [comment]
ping @iglpdc

**Comment by iglpdc** [comment]
@acabunoc, @gvwilson I didn't have the chance to teach SQL in a workshop since that...

I can write a PR adding this to the instructors' guide as suggested in #24.

**Comment by gvwilson** [comment]
Can this one now be closed?
