### ISSUE TITLE
  instr function not available in SQLite 3.7.13 and older

### ISSUE THREAD

**Issue by danabauer** [swcarpentry/sql-novice-survey#13]
One of the challenge questions in SQL lesson 04-calc requires students to use the instr function. This function wasn't introduced until 3.7.15 and it's likely students using the pre-installed version of SQLite on Mac OS X and Linux will have older versions. Perhaps add a note in the lesson? Or prompt students to check their version of SQLite in the installation instructions and upgrade?

**Comment by wking** [comment]
On Sat, Jan 03, 2015 at 10:29:06AM -0800, Dana Bauer wrote:
> One of the challenge questions in SQL lesson 04-calc requires
> students to use the instr function. This function wasn't introduced
> until 3.7.15 and it's likely students using the pre-installed
> version of SQLite on Mac OS X and Linux will have older versions.

The original instr content comes from 61ae6ffb (First three lessons on
SQL for beginners, 2013-11-09).  The commit message there doesn't
motivate this particular example (it's adding a lot of other content
too ;), and I don't see notes in instructors.md explaining the
approach taken by this lesson.  However, when I used this lesson at
2014-03-uwash I felt like there was too much time spent on “look at
these fancy queries we can build” and not enough on “here's how to
organize a schema and perform simple joins”.  I'd rather focus on the
big picture in this lesson, so students have a solid foundation after
the lesson.  They can use search engines and their SQL engine's docs
to fill in their knowledge of fancy SQL search terms as the need
arises, but without a need to motivate it, I had trouble making the
fancy queries exciting.

**Comment by gvwilson** [comment]
I think the exercise's content and the need to have the right version of SQLite installed are separate issues - please open a separate PR for the former.

**Comment by wking** [comment]
On Sat, Jan 03, 2015 at 03:02:10PM -0800, Greg Wilson wrote:
> I think the exercise's content and the need to have the right
> version of SQLite installed are separate issues - please open a
> separate PR for the former.

I've moved the bigger-picture content issue into #14.

**Comment by henrykironde** [comment]
Thanks @danabauer, for this good contribution and idea. Currently, I would want to think that we have this covered especially with the new sqlite platform used that requires new versions. Please feel free to reopen this issue or reference it.
