### ISSUE TITLE
change extension: survey.db  --> survey.sqlite

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/sql-novice-survey#130]
When teaching this lesson using the Firefox add-on, the add-on expects the file to end in `sqlite`. Renaming the file would remove one step when explaining how to import the data.

**Comment by knuths** [comment]
This change gets a bit confusing when following the instructions in the lessons.  There is says to download survey.db and then open up survey.sqlite in the command line.  Then no data is loaded.
