### ISSUE TITLE
Very useful visualisation of code for joins 

### ISSUE THREAD

**Issue by dvanic** [swcarpentry/sql-novice-survey#132]
Perhaps share link with students? It's just so useful for getting the right code for the different types of joins (as well as knowing what an "outer" or "inner" or "right" joins are, which are not intuitive for non software devs, but super-easy to understand once you get them).

[http://sql-joins.leopard.in.ua/](http://sql-joins.leopard.in.ua/)

/sorry if this is the wrong place to leave a comment/

**Comment by acabunoc** [comment]
Thansk for the pointer @dvanic! And thanks @Deborah-Digges for adding it into the lessons. Great addition 👍
