### ISSUE TITLE
Check links to .db files and others.

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/sql-novice-survey#137]

**Comment by njamescouk** [comment]
I've just downloaded survey.db (with a view to regenerating the diagram) but it uses ident as opposed to id. Is survey.db redundant?

**Comment by gvwilson** [comment]
Apologies - link was incorrect.  New link posted - please let us know if 
that fixes it.

**Comment by njamescouk** [comment]
looks good, thanks
