### ISSUE TITLE
Shift some focus from complex query construction to schema design

### ISSUE THREAD

**Issue by wking** [swcarpentry/sql-novice-survey#14]
I layed out my reasoning and past experience [here](https://github.com/swcarpentry/sql-novice-survey/issues/13#issuecomment-68605215), but I'm splitting this out into a separate issue because it's partially independent of the SQLite support for `INSTR` (which is the focus of #13).  I initially responded there because I don't think we should be talking about `INSTR` in a novice SQL lesson at all, and I'd rather we spent that time getting students comfortable mapping between the real world an a database schema.

**Comment by acabunoc** [comment]
@wking - I like this -- I normally spend more time on schema (how columns, rows, tables interact with each other) at the very beginning and cut out fancy queries if we have a time restriction. I've been meaning to work on a similar big picture change.

**Comment by wking** [comment]
On Sun, Feb 01, 2015 at 12:21:07PM -0800, Abigail Cabunoc wrote:
> I normally spend more time on schema (how columns, rows, tables
> interact with each other) at the very beginning and cut out fancy
> queries if we have a time restriction.

Instead of planning on not getting to the fancy queries, I'd rather
just drop them ;).  Without a need to hook them in, I don't expect
that most of these queries will stick in student's minds.  We just
need to show them a few different things you can do.

I'd probably show a ‘LIKE %substr%’ example and then say “Basically,
if you need a particular search / aggregation, there's probably
already SQL syntax for it.  The reference file links to the docs for
SQLite, PostgreSQL, and a number of other popular engines so you can
find what you need.  Then I'd browse through SQLite's LIKE docs live
and point out how you'd find what you need without getting
overwhelmed.

After that, instead of getting into the weeds with more esoteric
queries, I'd just have students split up into groups and build a
database for a class grade list (tables for students, assignments, and
grades linking students with assignments) or something else that
seemed appropriate for the audience (we want them to know the problem
domain well enough that the only challenge is translating to SQL).

**Comment by acabunoc** [comment]
I like this plan. Thanks @wking!

**Comment by henrykironde** [comment]
Thanks folks for the good contributions and ideas. Currently, I would want to think that we have a stable set of lesson structure that has been designed with these issues in mind for the past few years. I will close this and we hope to grow and expand as new ideas come in. Please feel free to reopen this issue or reference it.
