### ISSUE TITLE
Compare to Excel early on

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/sql-novice-survey#142]
From https://github.com/swcarpentry/bc/issues/750:

A learner writes: "I want to know in the first part of the page what I can do in SQL that I cannot do in Excel. Begin with a short example of a data manipulation (changing a person’s name when they get married, changing a sequence accession for a set of bioinformatics results) that is easy to do with SQL, but much more challenging (or error prone) with spreadsheets."

**Comment by henrykironde** [comment]
Since not much has been added to this, I will close it and anyone willing to reopen it, please feel free.
