### ISSUE TITLE
First exercise in the Filtering Lesson

### ISSUE THREAD

**Issue by maglet** [swcarpentry/sql-novice-survey#147]
At a workshop i taught a couple of weeks ago, there was a lot of confusion about the first exercise in the filtering lesson:

> Suppose we want to select all sites that lie more than 30 degrees from the poles. Our first query is:
> 
> Fix this query:
> SELECT \* FROM Site WHERE (lat > -60) OR (lat < 60);
> Explain why this is wrong, and rewrite the query so that it is correct.

I think people understood that the solution is to replace OR with AND, but they were trying to use this query on survey.db to check their work. Because none of the sites in survey.db are less than 30 degrees from the poles, you get the same output from the query using AND/OR. This confused a lot of people. Could we change the exercise so that it excludes some sites from the dataset, or change the dataset to include sites nearer to the poles?
- Tobin

**Comment by tpoisot** [comment]
Yes -- open a PR.

**Comment by maglet** [comment]
Great, I added to a previous PR I have about changing the file name in the lessons to reflect the file provided.

**Comment by acabunoc** [comment]
thank all 💯  closing now that we have @maglet's amazing PR

**Comment by maglet** [comment]
Woo!
