### ISSUE TITLE
idea: use JavaScript-based SQL tool for teaching

### ISSUE THREAD

**Issue by zormit** [swcarpentry/sql-novice-survey#154]
When teaching the SQL lesson this week, I was not so happy with SQLiteManager.

- the GUI seems a bit cluttered, it's not intuitive what the different panes are for. I felt the need to explain where we are in every step.
- only one query can be displayed at a time: there is no progression visible for learners

There might be an alternative: Today I discovered [sql.js](https://github.com/kripken/sql.js/), which provides a JavaScript based SQL interpreter. There's even a [GUI](http://kripken.github.io/sql.js/GUI/) already available which might solve both problems mentioned above.

opinions?

PS: I already started a more general, but related [thread on the discussion-list](https://www.mail-archive.com/discuss@lists.software-carpentry.org/msg02832.html).

**Comment by vahtras** [comment]
I have not used the GUI myself, but I can see that sql.js can be a complement also to a command-line style of teaching. I like the clean interface, I think it is a good idea.

**Comment by henrykironde** [comment]
Thanks guys for this idea and contribution, we have adopted and new GUI which is currently working fine. We shall revisit this option if the need comes up. We really appreciate.
