### ISSUE TITLE
URL anchor tag gives 404 not found

### ISSUE THREAD

**Issue by debpaul** [swcarpentry/sql-novice-survey#155]
For this page  sql-novice-survey/_episodes/07-join.md 
this URL anchor tag https://github.com/swcarpentry/sql-novice-survey/blob/gh-pages/_episodes/reference.html#cross-product gives 404 not found.

**Comment by henrykironde** [comment]
http://swcarpentry.github.io/sql-novice-survey/reference.html#cross-product
Thank you @debpaul, this is fixed. please feel free to open if it happens again.
