### ISSUE TITLE
Solutions to SQL challenges

### ISSUE THREAD

**Issue by ncarchedi** [swcarpentry/sql-novice-survey#158]
The guidelines [here](http://swcarpentry.github.io/instructor-training/checkout/#what-makes-a-good-exercise) mention including solutions for all challenges, but I don't see a place to do this in the SQL episodes. Please advise :)

**Comment by gvwilson** [comment]
http://swcarpentry.github.io/lesson-example/ is the full documentation, 
and http://swcarpentry.github.io/lesson-example/04-formatting/ has notes 
on formatting - in particular, you will want something like this:

     > ## Challenge Title
     >
     > body of exercise
     >
     > > ## Solution
     > > text of solution
     > {: .solution}
     {: .challenge}

Thanks,
Greg

**Comment by remram44** [comment]
<table>
<tr><th>Episode</th><th>PR</th><tr>
<tr><td>01 Selecting Data</td><td><em>contributions welcome</em></td></tr>
<tr><td>02 Sorting and Removing Duplicates</td><td><em>contributions welcome</em></td></tr>
<tr><td>03 Filtering</td><td><em>contributions welcome</em></td></tr>
<tr><td>04 Calculating New Values</td><td><em>contributions welcome</em></td></tr>
<tr><td>05 Missing Data</td><td><em>contributions welcome</em></td></tr>
<tr><td>06 Aggregation</td><td><em>contributions welcome</em></td></tr>
<tr><td>07 Combining Data</td><td><em>contributions welcome</em></td></tr>
<tr><td>08 Data Hygiene</td><td><em>contributions welcome</em></td></tr>
<tr><td>09 Creating and Modifying Data</td><td><em>contributions welcome</em></td></tr>
<tr><td>10-11 Programming</td><td>see list at #178</td></tr>
</table>

**Comment by Haleluyaluya** [comment]
Looking for missing Data
You may use Null values for your attributes such as your attribute=NULL or 
you may use single quotes as value for the attribute 
such as on my student table I am looking if there are any name ("sname') or sex ("ssex) values left empty:
       select * from Student where sname=' ' or ssex=' ';
This retrieves for me if null values exist in two columns of the relation

**Comment by slimlime** [comment]
Previous February solution for Ordering When Concatenating https://github.com/swcarpentry/sql-novice-survey/commit/ac09460f88a8aa197deff5197a5f0e5a8a21ace6

Oops, reverted 50095d2 back to no solution? 
Added solution to challenge: Ordering When Concatenating ( #158 #223)

Uninformative revert Merge `commit` message r4space@50095d2 does not elaborate on if there was an issue with the solution, or if the formatting was broken?

**Comment by henrykironde** [comment]
Should be fine working fine now
