### ISSUE TITLE
Absolute link to "/raw/gh-pages" breaks in lesson release

### ISSUE THREAD

**Issue by twitwi** [swcarpentry/sql-novice-survey#163]
The index page have the following links

     [survey.db]({{ site.github.repository_url }}/raw/gh-pages/files/survey.db)

This explicitly links to the currently latest version of db file, which can be a good thing (propagate fixes more rapidly) or a not-so-good thing (possible incoherence between the lesson people are reading and the db file they might be downloading).

This semi-absolute link also causes problems (by default) in the releases, as in http://swcarpentry.github.io/swc-releases/2017.02/sql-novice-survey/

I have partial information on this and there might be other reasons for this link, but my recommendation would be to switch to a relative link like "files/survey.db" or "./files/survey.db".

**Comment by henrykironde** [comment]
fixed
