### ISSUE TITLE
Firefox 53 and SQLite add-on

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/sql-novice-survey#169]
As mention in https://blog.mozilla.org/addons/2017/02/28/compatibility-for-firefox-53/

> Firefox 53 will be released on April 18th. Here’s the list of changes that went into this version that can affect add-on compatibility.

Could someone test if this is going to break the add-on that we use?

**Comment by fmichonneau** [comment]
I just checked Firefox 53 on ubuntu, and there is no problem with the SQLite addon.

**Comment by rgaiacs** [comment]
I'm closing this based on @fmichonneau reply.
