### ISSUE TITLE
_episodes/01-select Objectives suggestions

### ISSUE THREAD

**Issue by jbkieffer** [swcarpentry/sql-novice-survey#170]
As part of instructor checkout, I'm offering suggestions to make the objectives for 01-select more specific and demonstrable. In support of objectives 1 and 2 I have suggested activities that could be incorporated into instructor notes. 

**Objectives**
Learners will:
- Identify individual elements of a database in order to demonstrate knowledge of the differences among tables, records (rows), and columns (fields).
- Differentiate between example managers and content in order to understand the difference between a database manager and a database.
- Practice writing SQL queries that select all values for specific columns (fields) from a single table in order to begin manipulating data outputs from a relational database.

**Suggested activities for instructor notes:**
Objective 1:
Instructor types a heading into the workshop etherpad and asks learners to type in an example of the correct element, with all examples taken from the lesson dataset, e.g.:
Type one table name:
Type one column name:
Type one observation from a row in the table named Person:

Objective 2:
Instructor types into the workshop etherpad a mixed list of managers and content drawn from everyday life and then asks learners to identify which is which using the red and green sticky notes. For example, a mixed list might include Outlook, Gmail, Email, Contacts. The instructor asks, "Show your red sticky if you think Outlook is a manager. Show your green sticky if you think Email is a manager." The idea of the exercise is to fulfill the objective by relating the unfamilar concept of a database manager and a database to more familiar managers and the content or data they manage.

**Comment by henrykironde** [comment]
Thanks @jbkieffer for the issue. We discussed some of these issues in the maintainer meetings and with the instructor and hope some ideas may be adopted in the future.
