### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/sql-novice-survey#177]
We recently gave the SQL lesson for the first time, and I wanted to share some of the installation issues (which took an hour to fix) we had.

- Windows, learner had installed Anaconda, but sqlite was not installed. Solution: open Anaconda Prompt, write ‘conda install sqlite=3’
- same problem, but above solution didn’t work as learner did not have permission to install in the Anaconda3 folder (even though they were able to install Anaconda)
- Running Windows installer was blocked by antivirus software; solutions: variable, ideally learner can temporarily disable the antivirus software or create an exception (or designated trusted folder for downloads); alternatively provide installer on USB sticks
- Windows 10 (maybe also8 and 7), learner using SWC windows installer: sqlite3 is not added to PATH-variable; solution: manually add

**Comment by heereman** [comment]
I could maybe add that some learners called for some instructions to test if everything is running properly.

**Comment by fonnesbeck** [comment]
Yes, the windows installer for SQLite that is on the workshop website template does not add SQLite to the path, nor does it tell where the app is installed, making it unusable for learners. We were forced to grab a binary from SQLite.org and place it in the working directory. This ate up about 20 minutes of workshop time trying to resolve.

**Comment by henrykironde** [comment]
Closing because we are not using the SWC windows installer currently and we have new releases of Sqlite which I do think has solved some of the bugs. We also have added the finding in the instructions. We shall open in case we get a new report on this.
