### ISSUE TITLE
an exercise in 06-agg implies group_concat has an ordering feature

### ISSUE THREAD

**Issue by DanielBaird** [swcarpentry/sql-novice-survey#180]
The last exercise in episode 06 Aggregation demonstrates a `group_concat` and asks if there's a way to order the concatenated items.

As far as I can tell SQLite doesn't have a way to order `group_concat` without doing a subquery, and the lesson doesn't teach subqueries. The MySQL version of `group_concat` does have an `order by` option; I suspect this exercise is left over from a MySQL version of the lesson.

The simplest resolution would be to remove the exercise, but ideally it can be re-written with a different challenge.

**Comment by kokbent** [comment]
Agreed with this. Was searching high and low for solution for this only to find out that sqlite's group_concat doesn't do order by

**Comment by henrykironde** [comment]
@DanielBaird, @kokbent @yeemey @eugenesit feel free to provide any feedback on this PR #345. Well appreciated.
