### ISSUE TITLE
quotations for strings

### ISSUE THREAD

**Issue by wtong5456** [swcarpentry/sql-novice-survey#184]
In module 3 'Filtering' it is worth mentioning that either single or double quotation marks can be used in queries. I.e. SELECT * FROM Visited WHERE site='DR-1'; or SELECT * FROM Visited WHERE site="DR-1"; can be used.

**Comment by pgmccann** [comment]
This is not universal across database managers - in PostgreSQL only single quotes can be used to specify string values by which to filter (double quotes can be used to create and refer to case-sensitive table and column names) - I believe this is in accordance with the ANSI SQL standard. I would suggest that the use of single quotes be at least encouraged here.

**Comment by danmichaelo** [comment]
Agree, we should encourage single quotes even though double quotes works. The [https://www.sqlite.org/faq.html SQLite FAQ] also does this:

> Use single-quotes, not double-quotes, around string literals in SQL. This is what the SQL standard requires.
