### ISSUE TITLE
Mentioning 'NOT' or '!=' in 'Filtering' episode

### ISSUE THREAD

**Issue by kokbent** [swcarpentry/sql-novice-survey#185]
I was running through the SQL episodes to prep for the workshop next week, and found out about this issue. In the 'filtering' episode, where we introduce about the use of WHERE and AND, OR, LIKE to filter the queries, NOT or '!=' is missing from the examples and explanations. This kind of make the "Key Points" section looks weird because one of the points is: "Use AND, OR, and NOT to combine tests". In addition, the "Unions" challenge in the next episode ("Calculating New Values") would have been easier if the student knows how to use NOT or '!='. And in the "Missing Data" episode, '!=' is used in quite a few occasions without any introduction to the notation prior to it.

I think it would be nice to add a line or two about them in the 'Filtering' episode because for several minutes I was trying to figure out if we're not supposed use the 'NOT' operator or '!=' for some reason.

**Comment by henrykironde** [comment]
Thanks to @kokbent for the issue. I believe this has been resolved. Re-open in case you still think there could be improvements in that part.
