### ISSUE TITLE
Issues at instructors.md

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/sql-novice-survey#19]
From https://github.com/swcarpentry/lesson-template/blob/gh-pages/tools/check.py:

- [ ] Heading at line 58 should be level 2
- [ ] Heading at line 64 should be level 2
- [ ] Heading at line 91 should be level 2
- [ ] Heading at line 127 should be level 2
- [ ] Heading at line 171 should be level 2
- [ ] Heading at line 180 should be level 2
- [ ] The document links to 01-one.html, but could not find the expected markdown file /tmp/sql/01-one.md
- [ ] The document links to 02-two.html, but could not find the expected markdown file /tmp/sql/02-two.md

**Comment by gvwilson** [comment]
This one is out of date (but there are still problems with this file).
