### ISSUE TITLE
Changing Print Statement in Programming with Databases - Python

### ISSUE THREAD

**Issue by mfixstsci** [swcarpentry/sql-novice-survey#195]
For the lesson [Programming with Databases - Python](http://swcarpentry.github.io/sql-novice-survey/10-prog/), in the second example where you show the dangers of SQL injection, there is a print statement that uses the python 2 syntax to print to screen. To avoid compatibility issues with python 3 it might be worth while to change it from:

```python
print "full name for dyer:", get_name('survey.db', 'dyer')
```

to something like:

```python
print("full name for dyer: {}".format(get_name('survey.db', 'dyer')))
```

**Comment by donalus** [comment]
This fix was completed and is pending in the following Pull Request #162: https://github.com/swcarpentry/sql-novice-survey/pull/162/commits/3811c3a3c892c55fa78ad8336d38cfc3049def92

**Comment by franktoffel** [comment]
I was going through the lessons today and noticed it.
Maybe it will be good to indicate explicitly how to run the Python script from the terminal.
