### ISSUE TITLE
Field labels for Person and Visited tables in diagram

### ISSUE THREAD

**Issue by RichardPBerry** [swcarpentry/sql-novice-survey#197]
Hi there,

 In the diagram on the Combining Data episode the field labels for the Person and Visited tables are given as `ident`.

http://swcarpentry.github.io/sql-novice-survey/07-join/

These need to be changed to `id` to be consistent with the schema and rest of the text.

**Comment by donalus** [comment]
These changes were completed in a pending Pull Request: https://github.com/swcarpentry/sql-novice-survey/pull/156/commits/f73fea98cef3fe693f083c6ba39f61306d8ef0c5
