### ISSUE TITLE
Missing files motivation.md and discussion.md

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/sql-novice-survey#20]
From https://github.com/swcarpentry/lesson-template/blob/gh-pages/tools/check.py:

- [ ] The document links to motivation.html, but could not find the expected markdown file /tmp/sql/motivation.md
- [ ] The document links to discussion.html, but could not find the expected markdown file /tmp/sql/discussion.md

**Comment by gvwilson** [comment]
These files now exist (but need to be filled in).
