### ISSUE TITLE
Suggestion: Field names discussion - teaching moments or just fix?

### ISSUE THREAD

**Issue by dlstrong** [swcarpentry/sql-novice-survey#202]
While the SWC SQL lesson has much friendlier field names than the social science one (q4xii anybody?), there are still some oddities in the field names here.

I've been using them as teaching moments -- "remember the spreadsheet sessions section on helpful column names? There are two fields named 'id' in different tables; here's why it would be more helpful to have this field named visit_id and this other one named person_id; here's why 'taken' is not a helpful field name because of the number of ways the desired data input could be misinterpreted, and why something like fkey_visit_id would be more informative both to data contributors and to future researchers looking at the same dataset".

So I'm torn on whether to actually suggest changes to the fields or whether to suggest edits in the text that point out the potential for field name improvements, with some leanings toward the latter.

What does the community think?

**Comment by gcapes** [comment]
I'm just working through the lesson for the first time and I'm confused by what the `taken` variable means. I could well have missed it, but I don't think it's ever introduced/explained?
I think either explaining what this heading means, or renaming it to something more self-explanatory would be useful.
