### ISSUE TITLE
The `IN` keyword is never introduced

### ISSUE THREAD

**Issue by remram44** [swcarpentry/sql-novice-survey#203]
Follows up on #187

One of the challenges in chapter 05 needs the use of the `IN` keyword, however it is never introduced. It should probably be added to chapter 03.

This keyword is very powerful, and often used for instance with subqueries.

**Comment by gcapes** [comment]
This is now explained in episode 3, so should this issue be closed?

**Comment by remram44** [comment]
Wow, good catch! The `IN` keyword was introduced in episode 03 the whole time. I don't know how I missed this, I will close this issue, thanks again @gcapes!
