### ISSUE TITLE
Introducing database terminology

### ISSUE THREAD

**Issue by cmbz** [swcarpentry/sql-novice-survey#207]
I suggest that the introduction-to-key-database-concepts section at the beginning of the Selecting Data (http://swcarpentry.github.io/sql-novice-survey/01-select/) Lesson be extracted and made into its own brief lesson (e.g. 10 minutes), preferably with a diagram.

This would make it possible for learners in this lesson, as well as other database-related lessons, to quickly find/refer to database concepts as needed.

**Comment by r4space** [comment]
Hi @cmbz 

I really like the idea of a diagram, have made such for teaching other lessons before and generally goes down well.  Also means people might not be taking such frantic notes in the early stages.

Would you be up to proposing a diagram?  Would have to get review by community too but I think worth exploring.

Question of it being a separate section or not needs some more discussion, will see who else chips in here.

**Comment by mgibbswalton** [comment]
By diagram, are you referring to a diagram the differences between tables, records, and fields?

**Comment by mgibbswalton** [comment]
![image](https://user-images.githubusercontent.com/37548332/55652314-c4da1d00-57b0-11e9-9347-377271974e60.png)

**Comment by henrykironde** [comment]
I am closing this issue due to less activity. Free free to open the issue again

**Comment by henrykironde** [comment]
Duplicate: #228
