### ISSUE TITLE
Order of columns in SELECT statements

### ISSUE THREAD

**Issue by elibtronic** [swcarpentry/sql-novice-survey#211]
In the introductory SQL lesson (http://swcarpentry.github.io/sql-novice-survey/01-select/) there is mention of re-using columns and picking any columns you'd like for your select. It might be worth explicitly mentioning (or via an example) that the choice of columns doesn't need to read left to right.

EG.
`SELECT id, id, id FROM Person;`
is example

Could also have
`SELECT personal, id, family, id FROM Person `

**Comment by remram44** [comment]
Indeed it might be good to not have all the examples use the columns in order. PR welcome!

**Comment by henrykironde** [comment]
I am closing this issue due to less activity. Free free to open the issue again
