### ISSUE TITLE
Selecting Data: Switch .mode and .header statements to be run after the first query

### ISSUE THREAD

**Issue by nickrsan** [swcarpentry/sql-novice-survey#217]
Practicing this today, my partners, who aren't SQL users, were confused when I first did the lesson in the order that it's in, where `.mode column` and `.header on` are used before selecting any data, and liked it when I tried a variation later, where I selected data first, showed them that it's hard to read, then ran each command and the select statement in turn, showing the change in output as a result.

As constructed, I think those become magic commands that aren't meaningful enough to be remembered. I think that this change could be created in a way that keeps any time increase to a minimum, and it can also help in discussion of what fields/rows are as learners can see the output shift from a jumble to something structured. I'm curious how other instructors perceive this - I know these commands aren't the point of the exercise, but think learners will want to remember them in the future.

Just a suggestion - if maintainers approve, I'd be happy to submit a pull request with a suggested change. Thanks for creating this - I chose this lesson for my practice in the teacher training because it looked like it was in great shape and would be great for new users, so thanks for making it!

**Comment by remram44** [comment]
Showing what happens if you don't type this, and why we prefer it, is definitely a good idea.

When I gave the lesson, I also mentioned that those could be put in `.sqliterc` so you don't have to type it every time.

**Comment by henrykironde** [comment]
Both ideas are good. Lets combine them and come out with a description that includes adding these to .sqliterc file and what this file is for.
