### ISSUE TITLE
Missing solution to challenge: `Selecting Major Site Identifiers`

### ISSUE THREAD

**Issue by gcapes** [swcarpentry/sql-novice-survey#220]
I'm not clear what this challenge is asking. Is it something like this?
`SELECT DISTINCT  substr(site,1,instr(site,'-')-1) as MajorSite from Visited;`

If so I can edit the wording and submit a PR.

**Comment by remram44** [comment]
Hi @gcapes,

Missing solutions to challenges are tracked at https://github.com/swcarpentry/sql-novice-survey/issues/158#issuecomment-361410112

**Comment by remram44** [comment]
I think this is a good solution! If you want you can submit a pull request and I'll update the list. Thank you for your contribution! It looks like we can get all the challenges solved soon at this rate.
