### ISSUE TITLE
Missing solution to challenge: Averaging with NULL

### ISSUE THREAD

**Issue by gcapes** [swcarpentry/sql-novice-survey#221]
Ep 6
I think the answer is 3, but can't see how I can easily test this. Some discussion of the solution and/or a method of testing this would be very useful.

**Comment by remram44** [comment]
Hi @gcapes,

Missing solutions to challenges are tracked at https://github.com/swcarpentry/sql-novice-survey/issues/158#issuecomment-361410112

**Comment by remram44** [comment]
The answer is indeed 3:
```sql
SELECT AVG(a) FROM (
    SELECT 1 AS a
    UNION ALL SELECT NULL
    UNION ALL SELECT 5);
```
i.e. the NULL is not counted, instead of counting for 0.
