### ISSUE TITLE
Missing solution to challenge: Ordering When Concatenating

### ISSUE THREAD

**Issue by gcapes** [swcarpentry/sql-novice-survey#223]
Ep 6
No solution given.

**Comment by henrykironde** [comment]
@Thanks @gcapes, could you be more descriptive so that the community could follow easily. You could provide a link or code block.

**Comment by gcapes** [comment]
That's the start of that challenge, yes. There's also the second part:
>```William Dyer, Frank Pabodie, Anderson Lake, Valentina Roerich, Frank Danforth```
>Can you find a way to order the list by surname?

**Comment by remram44** [comment]
Hi @gcapes,

Missing solutions to challenges are tracked at https://github.com/swcarpentry/sql-novice-survey/issues/158#issuecomment-361410112
