### ISSUE TITLE
What are fixmes?

### ISSUE THREAD

**Issue by karinlag** [swcarpentry/sql-novice-survey#23]
Are fixmes things that should be fixed, i.e. something is wrong, or are they lesson challenges? I get confused by the naming - some of them at least seem to be potential lesson challenges.

**Comment by gvwilson** [comment]
FIXME is something that needs to be fixed or replace - in the case of 
challenges, it signals that we need a better title for the challenge.

**Comment by PBarmby** [comment]
Some of the FIXMEs in this repo were addressed by PR [#10](https://github.com/swcarpentry/sql-novice-survey/pull/10) which is just awaiting review.
