### ISSUE TITLE
Data Hygiene: Naming being a poor example.

### ISSUE THREAD

**Issue by clintonroy** [swcarpentry/sql-novice-survey#236]
Assuming everyone has a first and a last name is old world thinking, and is not current best practice.

**Comment by henrykironde** [comment]
@clintonroy correct, but since this is a tutorial I think keeping the assumption is okey. Someone else could argue that we need a middle name.
However, If you have a good replacement for the example, that would be great.

**Comment by clintonroy** [comment]
Yeah, I'm having a think, give me a few weeks :)

**Comment by remram44** [comment]
[I remarked on that too](https://github.com/swcarpentry/sql-novice-survey/pull/226#discussion_r180134243), thanks for bringing it up. Indeed this works for the US and a lot of Western countries but is really not universal. 

I don't know if swapping out the example completely is a good idea, I think we should try and introduce people to those notions before they build websites that only work for Americans.

**Comment by henrykironde** [comment]
Thanks everyone. Localization and globalization are good ways forward, but these should be thought of as abstract data examples. Changing the data would require several changes throughout the lesson and verification. That is something that will need a group of us to work on to add. For now, I am closing this issue. Please feel free to reopen it for fresh input.
