### ISSUE TITLE
Ep. 09: Broken link to date/time values discussion

### ISSUE THREAD

**Issue by yeemey** [swcarpentry/sql-novice-survey#237]
The link referring to a discussion on date/time values in [Ep. 09 Creating and Modifying Data](http://swcarpentry.github.io/sql-novice-survey/09-create/) doesn't work (links back to the same lesson).

> Most databases also support Booleans and date/time values; SQLite uses the integers 0 and 1 for the former, and represents the latter as discussed [earlier](http://swcarpentry.github.io/sql-novice-survey/09-create/#a:dates). 

As far as I can tell, date/time is discussed in:
1. the **Date Types** callout in [Ep. 03 Filtering](http://swcarpentry.github.io/sql-novice-survey/03-filter/)
2. the solution for the **Identifying Atomic Values** problem in [Ep. 08 Data Hygiene](http://swcarpentry.github.io/sql-novice-survey/08-hygiene/).

Can this be consolidated?

**Comment by remram44** [comment]
Indeed this link never pointed anywhere. I also feel like those should be consolidated, or maybe even turned into a chapter (though [the official documentation page](https://sqlite.org/lang_datefunc.html) is pretty clear and short).

**Comment by henrykironde** [comment]
@remram44, looks like you fixed this. Did you?

**Comment by remram44** [comment]
No it is still broken, it wasn't fixed by #244

**Comment by remram44** [comment]
We should fix this
