### ISSUE TITLE
0th lesson with db install and .schema/.tables?

### ISSUE THREAD

**Issue by karinlag** [swcarpentry/sql-novice-survey#24]
I am thinking of adding a 0th lesson which would do the following:

- Show explicitly where to get the db file (I had to go digging) and how to get it into sqlite.

- Show how to figure out which tables you've got (.tables) and what kinds of things are in them (.schema). My reason for wanting to add these are to help them see which tables we've got and which column names  they have. I always tend to forget what they are, hence my idea of showing how to see what they are.

I am especially unsure about .schema. I myself am reasonably comfortable with sql, so I am not confused by the resulting CREATE TABLE thing that appears, but I do see the potential confusion for the student. 

Any comments/suggestions on this?

**Comment by gvwilson** [comment]
On 2015-01-31 12:31 PM, karinlag wrote:
>
> I am thinking of adding a 0th lesson which would do the following:
>
>  *
>
>     Show explicitly where to get the db file (I had to go digging) and
>     how to get it into sqlite.
>
I think this belongs in the instructor's guide (or in the setup notes in 
the workshop template? but that would tie the template too closely to a 
particular lesson)
>
>  *
>
>     Show how to figure out which tables you've got (.tables) and what
>     kinds of things are in them (.schema). My reason for wanting to
>     add these are to help them see which tables we've got and which
>     column names they have. I always tend to forget what they are,
>     hence my idea of showing how to see what they are.
>
Yes please - I taught SQL yesterday, and the first thing I found myself 
doing was `.schema`.  We should also get a readable diagram of the 
tables and their contents into the repository - Elizabeth Patitsas had 
one, and there's something in the HTML of the old notes.

**Comment by karinlag** [comment]
On 31.01.2015 19:46, Greg Wilson wrote:
>
> On 2015-01-31 12:31 PM, karinlag wrote:
>  >
>  > I am thinking of adding a 0th lesson which would do the following:
>  >
>  > *
>  >
>  > Show explicitly where to get the db file (I had to go digging) and
>  > how to get it into sqlite.
>  >
> I think this belongs in the instructor's guide (or in the setup notes in
> the workshop template? but that would tie the template too closely to a
> particular lesson)

Hm. This goes kind of to lesson design philosopy, i.e. should somebody 
from the outside be able to run our lessons straight off, or not. Right 
now, without a setup file describing where or how to get the data, they 
can't. I see that this is the case for the python lessons too, however, 
so I will leave this one for now.


>  > Show how to figure out which tables you've got (.tables) and what
>  > kinds of things are in them (.schema). My reason for wanting to
>  > add these are to help them see which tables we've got and which
>  > column names they have. I always tend to forget what they are,
>  > hence my idea of showing how to see what they are.
>  >
> Yes please - I taught SQL yesterday, and the first thing I found myself
> doing was `.schema`. We should also get a readable diagram of the
> tables and their contents into the repository - Elizabeth Patitsas had
> one, and there's something in the HTML of the old notes.

Will go digging later this week.

K

**Comment by orchid00** [comment]
When I first started the SQL lesson, I also felt the need to do .table and .schema just to have a feeling of what I am dealing with. I found that the challenges start to quick like select the name of the sites, but how would students now what is the name of the field name? they can guess but what if it is not a common name?
