### ISSUE TITLE
Episoide 06-agg Add Definition of Aggregation

### ISSUE THREAD

**Issue by nathan-hook** [swcarpentry/sql-novice-survey#240]
During my training checkout demo, I completely blanked on what an aggregation actually is.

Having a definition at the beginning of the lesson might be useful.

Here is an example definition:

"An aggregate function performs a calculation on a set of values, and returns a single value."

Taken from this page:
[Aggregate Functions (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/functions/aggregate-functions-transact-sql?view=sql-server-2017)

**Comment by nathan-hook** [comment]
I don't feel as though those are definitions.  I feel as though those statements/questions get around the idea of what an aggregation is, but never actually define the word.

It would be like if we defined a database the following way:

> - Questions:  How can I store relational data in a storage mechanism that allows that data to be related to one another?
> - We want to get values out of our data.
> - Each of these statements, SELECT, UPDATE, DELETE

**Comment by nathan-hook** [comment]
I thought there was a pretty good definition of a database in the first lesson:
http://swcarpentry.github.io/sql-novice-survey/01-select/

> A relational database is a way to store and manipulate information. Databases are arranged as tables. Each table has columns (also known as fields) that describe the data, and rows (also known as records) which contain the data.

And to be clear, I am not trying to be conflictual, I am just mentioning something that would have helped me out while I was teaching the aggregations section.  :)

**Comment by remram44** [comment]
No worries! I am very open to a PR rewriting of this making it more explicit, I'm just not sure that the information you mentioned is missing. Indeed the current format is not as formal as an explicit definition; but is a formal definition required? I am just not sure.

**Comment by henrykironde** [comment]
Thank you for your input. I will close this for now since there hasn't been much input from the community. Feel free to reopen.
