### ISSUE TITLE
Episode 01-select Changing Order of Data and First Introduction with SQLite

### ISSUE THREAD

**Issue by nathan-hook** [swcarpentry/sql-novice-survey#241]
I feel as though it is weird that we discuss the usage of sqlite in the "Getting Into and Out Of SQLite" section and then move on to talk about the data.

Perhaps a better flow would be the following:
Changing Database Managers
talk about the data
Getting Into and Out Of SQLite
Checking If Data is Available

It feels like a bit of a tease to talk about SQLite and then the data and then back to SQLite.

**Comment by remram44** [comment]
I have no issue with the current flow. We mention that multiple database managers are available, that they all use SQL, and that to use SQL you need to get into SQLite.

I think there is also value in having that particular information as close to the top of the page as possible (the tables take a lot of space, having nothing but the challenges after that is preferable in my view).

To be clear, the only change in your recommendation is to move the description of the data up?

**Comment by nathan-hook** [comment]
Yes, you are correct, only moving the data description up was the recommendation.

**Comment by henrykironde** [comment]
Thank you for your input. I will close this for now since there hasn't been much input from the community. Feel free to reopen.
