### ISSUE TITLE
Bad link to CSV definition in glossary

### ISSUE THREAD

**Issue by cwant** [swcarpentry/sql-novice-survey#242]
Referring to the page: http://swcarpentry.github.io/sql-novice-survey/09-create/

During the exercise on Generating Insert Statements, there is a link to the definition of CSV in the glossary. The link points to the URL:

http://swcarpentry.github.io/sql-novice-survey/reference/#comma-separated-values

But it should really point to:

http://swcarpentry.github.io/sql-novice-survey/reference#comma-separated-values-csv

**Comment by henrykironde** [comment]
Thanks @cwant we have a fix for that.

**Comment by henrykironde** [comment]
fixed
