### ISSUE TITLE
Episode 01 - add .schema example for discovering available tables and columns

### ISSUE THREAD

**Issue by steven-schroeder** [swcarpentry/sql-novice-survey#248]
I realize the .tables example is provided to identify the tables in the currently open database.
Including .schema would also illustrate finding the available columns.

This would also require some additional definition and explanation of a database schema and column types.

---

**Comment by remram44** [comment]
Hi @steven-schroeder, thank you for the feedback. That does sound like a good idea: while I tend to just select a few rows to get a sense of the contents of a table, getting the precise column types is done through `.schema` and this should probably be stated somewhere (in episode 01?)

**Comment by henrykironde** [comment]
Solved in #271
