### ISSUE TITLE
Current gh-pages links fail to resolve

### ISSUE THREAD

**Issue by henrykironde** [swcarpentry/sql-novice-survey#252]
This builds fine  locally but the current remote fails to find the links.

Example. http://swcarpentry.github.io/sql-novice-survey/01-select/index.html
Try to check links for `relational database`, `tables` , etc.

**Comment by remram44** [comment]
I thought I had grepped for that! I missed it in #249. This was also broken by https://github.com/carpentries/lesson-example/pull/127 cc @fmichonneau

**Comment by henrykironde** [comment]
Yah, I checked that too. I will run tests on this soon
