### ISSUE TITLE
wrong data type on line #37 episode 9 "Create"

### ISSUE THREAD

**Issue by arockenberger** [swcarpentry/sql-novice-survey#263]
In episode 9 "Create" there's a mistake on line 37:
It reads 
`CREATE TABLE Survey(taken integer, person text, quant real, reading real);`
It should read
`CREATE TABLE Survey(taken integer, person text, quant text, reading real);`

**Comment by remram44** [comment]
Hi @arockenberger, thanks for letting us know! Indeed this is wrong, we'll fix it.

**Comment by danmichaelo** [comment]
Didn't notice that you created an issue at the same time! Good stuff :)
