### ISSUE TITLE
Setup unclear for windows users

### ISSUE THREAD

**Issue by cabotzabriskie** [swcarpentry/sql-novice-survey#269]
When I ran through this lesson myself I had to figure out for myself how to get the bash shell working in the windows 10 environment. The setup section could really benefit from either a brief explanation of how to get this setup in windows 10 or an external link to the process such as: https://docs.microsoft.com/en-us/windows/wsl/install-win10. Right now it looks, at first glance, like this lesson is meant only for Linux users.

**Comment by remram44** [comment]
Hi @cabotzabriskie! I'm sorry if the instructions are terse, I don't use Windows myself, and my workshops are usually mostly Mac users.

bash is not strictly required to use SQLite3, however our lesson does include some bash snippets here and there. Whatever directions we can add for Windows users are certainly welcome. Do you feel like that page is sufficient for beginners  to setup bash? (e.g. how does one "Open PowerShell as Administrator"?)

Additionally, DB Browser for SQLite is always an option, and does not require any specific kind of terminal or shell.

Thank you for the feedback! Much appreciated

**Comment by cabotzabriskie** [comment]
Thanks for the quick response! I actually liked that the lesson forced me
to learn how to use the bash shell in windows (it's a useful thing that
I've been meaning to do, but never got around to). I found that page to be
pretty sufficient though I agree it may be worth mentioning that you have
to right click and select "run as Administrator" for the most beginner
level folks. Also, maybe a line about how anyone can use DB Browser for
SQLite regardless of OS would be good. This way if someone is doing this on
their own as a way to learn SQL, they don't feel like they need a
particular OS.

**Comment by henrykironde** [comment]
Closing because we are using git shell and have updated the instructions.
