### ISSUE TITLE
css formatting

### ISSUE THREAD

**Issue by orchid00** [swcarpentry/sql-novice-survey#27]
I have some suggestions on the template

Padding: 
*I see that most if not all tables need a bit more of bottom padding, the letters in the next paragraph are too close.
*Challenges on the other side are very spacious in between, and probably the question title should be a bit smaller. 
Colors:
*Table headers, I don't know if it is just me, but that blue is too dark to be combined with black... just saying

**Comment by r-gaia-cs** [comment]
@orchid00 Thanks very much for report this. We will try to address this at http://github.com/swcarpentry/styles/ so that all lessons get this fixed.

**Comment by orchid00** [comment]
great, thanks for the reply. It is the first time that I add issues, I was not sure whether is the right place or not. So should this be moved? or just advice for next time?

**Comment by r-gaia-cs** [comment]
> It is the first time that I add issues

Great report. :sparkles: 

> I was not sure whether is the right place or not.

You reported at the right place.

> So should this be moved? or just advice for next time?

If you like you could copy and paste it on a new issue at http://github.com/swcarpentry/styles/ **and mention as a duplication of this one by include the link `https://github.com/swcarpentry/sql-novice-survey/issues/27`**. This will help us reminder of this bug.

**Comment by orchid00** [comment]
Thanks! 

It's been copied :)

**Comment by acabunoc** [comment]
duplicate: https://github.com/swcarpentry/styles/issues/9 , closing
