### ISSUE TITLE
June 2019 Lesson Release checklist

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/sql-novice-survey#279]
If your Maintainer team has decided not to participate in the [June 2019 lesson release](https://carpentries.topicbox.com/groups/maintainers/T61c75ac1a8a89538/timeline-and-process-for-june-lesson-release), please close this issue.

To have this lesson included in the 18 June 2019 release, please confirm that the following items are true:

- [x] Example code chunks run as expected
- [x] Challenges / exercises run as expected
- [x] Challenge / exercise solutions are correct
- [x] Call out boxes (exercises, discussions, tips, etc) render correctly
- [x] A schedule appears on the lesson homepage (e.g. not “00:00”)
- [x] Each episode includes learning objectives
- [x] Each episode includes questions
- [x] Each episode includes key points
- [x] Setup instructions are up-to-date, correct, clear, and complete
- [x] File structure is clean (e.g. delete deprecated files, insure filenames are consistent)
- [x] Some Instructor notes are provided
- [x] Lesson links work as expected

When all checkboxes above are completed, this lesson will be added to the 18 June lesson release. Please leave a comment on carpentries/lesson-infrastructure#26 or contact Erin Becker with questions (ebecker@carpentries.org).

**Comment by henrykironde** [comment]
All look good to me. Thanks @fmichonneau and should I go ahead and close or leave this opened?

**Comment by ErinBecker** [comment]
@henrykironde - Thanks for working through this list. Please leave this open. @fmichonneau and I will be in touch with next steps!

**Comment by ErinBecker** [comment]
Hi Maintainers! - Just confirming that you're still planning on including your lesson in the June 2019 release. We'll be putting out a blog post tomorrow inviting contributors to work on issues that have been tagged as part of the release milestone, so if there are specific issues you're looking for community help with, please add them to that milestone. I'll make a first pass and add issues currently marked "help-wanted" to the milestone, but please feel free to update the milestone issue list at your convenience. Please let me know if you have any questions!

**Comment by henrykironde** [comment]
@ErinBecker, I personally think we should add it to the June2019 release. I am not sure what other Maintainers think, @remram44, @r4space.
However, I tried to test the checks but I guess we need some updates on style. Let me know what I am missing

**Comment by ErinBecker** [comment]
Thanks @henrykironde - I'm pinging @fmichonneau here so he can advise on whether style updates are needed. Great work on this and I'm looking forward to including this lesson in the release!

**Comment by ErinBecker** [comment]
Awesome work @swcarpentry/sql-novice-survey-maintainers and everyone else who contributed! This is just a quick message confirming that this lesson will be included in the release that @fmichonneau and I are preparing this week. The release is scheduled to go through on the 18th and to be announced to the community on the 24th. Please let us know if you have any questions! And congratulations again!

**Comment by fmichonneau** [comment]
lesson released! :tada: https://doi.org/10.5281/zenodo.3265271

**Comment by henrykironde** [comment]
Why do we have an error on the link?

**Comment by remram44** [comment]
It will take a little time for the DOI to work, in the meantime: https://zenodo.org/record/3265271

**Comment by henrykironde** [comment]
Looks nice, Thanks everyone for the great work, especially @remram44 with the Maintainers team,  and @fmichonneau, @ErinBecker, towards this new release.
