### ISSUE TITLE
Use .nullvalue for episode 5

### ISSUE THREAD

**Issue by juve** [swcarpentry/sql-novice-survey#280]
In episode 5, the table listings in the episode use the string '-null-' to represent null values, however the default output of sqlite3 displays null values as empty strings, which is a little confusing. It might be helpful if the episode included a call to `.nullvalue -null-` so that the output of the queries matches the documentation. Students are already familiar with changing the output format from `.headers` and `.mode`. Otherwise, the episode should at least acknowledge that sqlite3 is not going to display '-null-' by default.

**Comment by henrykironde** [comment]
@juve In case you have time feel free to add a line for that to the lesson.
