### ISSUE TITLE
survey.db needs rename for MacOS sqlite3

### ISSUE THREAD

**Issue by wdchild** [swcarpentry/sql-novice-survey#285]
When running this in sqlite3 on MacOS Sierra, survey.db does not work. You need to rename the file to survey.sqlite for it to open in Terminal. You may want to explain that in your course since it is geared for novices. Thanks.

**Comment by henrykironde** [comment]
Could you provide the version of sqlite3 you are using

**Comment by wdchild** [comment]
It turns out you need to rename the db to survey.sqlite.
I would just post that out in your documentation. My version was:

SQLite version 3.26.0

**Comment by henrykironde** [comment]
I think this has been resolved. Please feel free to open a new issue and tag this issue.
