### ISSUE TITLE
Does the Citation need to change?

### ISSUE THREAD

**Issue by henrykironde** [swcarpentry/sql-novice-survey#287]
Based on the release, do we change the citation?

https://zenodo.org/record/838776#.XTUWLpNKg1I
vs
https://zenodo.org/record/3265271#.XTUWZJNKg1I
ref #279

**Comment by ErinBecker** [comment]
@henrykironde - yep! Updating the citation would be great. You can use the default citation format that Zenodo uses, or can create a custom version that lists editors.
