### ISSUE TITLE
Ordering When Concatenating exercise in aggregation section has no solution

### ISSUE THREAD

**Issue by colinsauze** [swcarpentry/sql-novice-survey#288]
There's no solution for the "Ordering When Concatenating" exercise in the aggregation section (section 6).  I can't quite work out a complete solution which reports the answer on one line.
The nearest I can get is:

SELECT group_concat(personal || ' ' || family, ' ') FROM Person order by family;

which produces the wrong order:

William Dyer Frank Pabodie Anderson Lake Valentina Roerich Frank Danforth

or 

SELECT personal || ' ' || family FROM Person order by family;
Frank Danforth
William Dyer
Anderson Lake
Frank Pabodie
Valentina Roerich

produces the right order but uses multiple lines.

Does anyone have the correct solution to this?

**Comment by remram44** [comment]
(see also https://github.com/swcarpentry/sql-novice-survey/issues/158#issuecomment-361410112)

**Comment by remram44** [comment]
Honestly my suggestion is just removing this exercise.

**Comment by colinsauze** [comment]
Reading it did leave me wondering what the question is trying to teach. It feels like this isn't the most useful thing to know and requires some complex syntax to achieve it.

**Comment by edbennett** [comment]
One of our students yesterday pointed out that it could be done via `SELECT group_concat(personal || ' ' || family, ' ') FROM (SELECT * from Person ORDER BY family);`, but we don't currently teach subqueries anywhere (except one being used in the solution to the "Averaging with NULL" challenge, which itself is rather confusing)

**Comment by edbennett** [comment]
Oh, this was already discussed in #255

**Comment by henrykironde** [comment]
Thanks for the contribution. We have considered all the information and combined it to accept this PR #289
