### ISSUE TITLE
"Fix this query" exercise in filtering requires a bit too much spatial maths)

### ISSUE THREAD

**Issue by Denubis** [swcarpentry/sql-novice-survey#291]
Just ran into a problem in our workshop where we ran "Fix this query" and we went down something of a rabbit hole with identifying the poles and doing calculations of 48 or 42. (Which I didn't manage ... particularly well). 

Can we figure out a different way to tease out the difference between `and` and `or`?

**Comment by henrykironde** [comment]
Thanks @Denubis, sorry you had to go through that. I can see the explanation not going very well. I will amend that exercise by the end of the day. I will ping you to get your input on the changes.

**Comment by henrykironde** [comment]
@Denubis,please have a look at the PR and let me know if it is clear

**Comment by Denubis** [comment]
Responded as a PR review in #292 (https://github.com/swcarpentry/sql-novice-survey/pull/292/files/2dc9011881b4dda485962b61a2307e1aa3b1809c)
