### ISSUE TITLE
Reference links broken on episode 1

### ISSUE THREAD

**Issue by Denubis** [swcarpentry/sql-novice-survey#309]
https://swcarpentry.github.io/sql-novice-survey/01-select/index.html has hyperlinked reference-words like "relational database"

Currently, these words 404 as they are pointing at https://swcarpentry.github.io/reference.html#relational-database. They should be pointing at https://swcarpentry.github.io/**sql-novice-survey**/reference.html#relational-database. Looking at the code, this is rendered as `to a [database manager]({% link reference.md %}#database-manager):` Which strikes me as a style conflict that @fmichonneau may need to be aware of?

**Comment by Denubis** [comment]
The person who reported this to me also noted that the hyperlinked references on the reference page don't always work or scroll appropriately. We may want to rethink ordering of glossaries so they are on top -- if only so that any time a hyperlink is clicked on the same page, the term is appropriately scrolled-to.

**Comment by henrykironde** [comment]
Thanks @Denubis for reporting this issue. Previously, It worked fine so I guess the folks at styles may be aware of this.

**Comment by henrykironde** [comment]
@fmichonneau, I know you have al ot on your desk but any update on this. Thank you

**Comment by fmichonneau** [comment]
I believe this can be closed as it has been addressed by https://github.com/swcarpentry/sql-novice-survey/pull/323
