### ISSUE TITLE
Episode 2 has 3 questions for the data, but only answers 2

### ISSUE THREAD

**Issue by jenna-jordan** [swcarpentry/sql-novice-survey#310]
Episode 2 begins with the text:

> In beginning our examination of the Antarctic data, we want to know:
       * what kind of quantity measurements were taken at each site;
       * which scientists took measurements on the expedition;
       * the sites where each scientist took measurements

The lesson walks through how to answer the first two questions, but never addresses the third. Furthermore, to fully answer the question of which *sites* each *scientist* took measurements at would require a join, which isn't covered until lesson 7.

So, I would propose simply deleting the third bullet point.

**Comment by henrykironde** [comment]
Thanks for pointing this out.
