### ISSUE TITLE
Update list of maintainers in README

### ISSUE THREAD

**Issue by danmichaelo** [swcarpentry/sql-novice-survey#319]
The list of maintainers in the README should reflect the people who have write access to the repo, so I think remram44 should be removed per [this comment](https://github.com/swcarpentry/sql-novice-survey/pull/289#issuecomment-515095044)?

**Comment by henrykironde** [comment]
Thanks you @danmichaelo, you have a great point.
I will try to send emails to all the maintainers and confirm if they still have time to work on the repo.

**Comment by henrykironde** [comment]
The issue was raised to the top-level management, and they are dealing with updating maintainers, so I guess these are maintainers who have agreed to continue the work on the project.
