### ISSUE TITLE
Broken links on several episodes and unclear exercise

### ISSUE THREAD

**Issue by SilviaBuonaiuto** [swcarpentry/sql-novice-survey#320]
I found several broken links (error 404) on different episodes  : 
episode 3 wildcard , episode 5 sentinel value, episode 9 referential integrity and cascading delete, episode 10 cursor. 
Moreover at the end of episode 4 (Calculating new values, http://swcarpentry.github.io/sql-novice-survey/04-calc/index.html ) the “in string” function and the substring function  are not very clear, maybe an example of use for these functions can be more useful than the exercise to understand them.

**Comment by henrykironde** [comment]
Thanks you @SilviaBuonaiuto, the team will look into this, I think it has something to do with the styles, but we shall get time and investigate

**Comment by henrykironde** [comment]
Thanks @SilviaBuonaiuto, I think this has now been covered in #323
