### ISSUE TITLE
Broken links on lesson 1 "Selecting Data"

### ISSUE THREAD

**Issue by GianlucaDamaggio** [swcarpentry/sql-novice-survey#322]
I found all broken links in the first part of [lesson 1](https://swcarpentry.github.io/sql-novice-survey/01-select/index.html) that should be used to explain what we are talking about and introduce better the elements.

I suggest fixing this to be very clear with peoples that are completely new with this kind of thing.

Best regards

**Comment by henrykironde** [comment]
Thank you @GianlucaDamaggio. I think this must be a styles problem. I will find out what changed. Sorry for the inconvenience.

**Comment by henrykironde** [comment]
@zkamvar has anything changed that we need to update with urls

**Comment by zkamvar** [comment]
@henrykironde,  sorry for not responding, I was on vacation last week. It looks like François has taken care of the issue in #323 by updating this repo to match the current styles repository.
