### ISSUE TITLE
Suggestion: run an example query before applying .mode column .header on

### ISSUE THREAD

**Issue by simonw** [swcarpentry/sql-novice-survey#326]
The first chapter suggests running `.mode column` and `.header on` here:

https://github.com/swcarpentry/sql-novice-survey/blob/97c367b8f441143ee7757f700d2d26db7b6d2124/_episodes/01-select.md#L214-L222

I think this advice would have more impact if the learner first executed a SQL query that showed what difference this makes. Something like this:

> Let's run our first SQL query, to see all of the rows in the Person table:
> ```
> sqlite> select * from Person;
> dyer|William|Dyer
> pb|Frank|Pabodie
> lake|Anderson|Lake
> roe|Valentina|Roerich
> danforth|Frank|Danforth
> ```
> This is a little hard to read. You can change some SQLite settings to make the output more readable.
> 
> First, set the output mode to display left-aligned columns.
> 
> ```
> sqlite> .mode column
> sqlite> select * from Person;
> dyer        William     Dyer      
> pb          Frank       Pabodie   
> lake        Anderson    Lake      
> roe         Valentina   Roerich   
> danforth    Frank       Danforth  
> ```
> Next turn on the display of column headers:
> ```
> sqlite> .header on
> sqlite> select * from Person;
> id          personal    family    
> ----------  ----------  ----------
> dyer        William     Dyer      
> pb          Frank       Pabodie   
> lake        Anderson    Lake      
> roe         Valentina   Roerich   
> danforth    Frank       Danforth  
> ```
>

**Comment by henrykironde** [comment]
Thanks @simonw, this is really good but some of these facts we leave to the instructor to talk about as they go through the chapters. If we add everything, we could probably run out of time. But please let folks know of some of these techiniques as you teach.
