### ISSUE TITLE
Add macOS details to the "Setup" page

### ISSUE THREAD

**Issue by simonw** [swcarpentry/sql-novice-survey#327]
http://swcarpentry.github.io/sql-novice-survey/setup.html currently only talks about Windows and Linux. It would be useful to cover macOS setup here as well.

**Comment by simonw** [comment]
It's quite possible that macOS has the `sqlite3` CLI tool available by default, but I'm not sure how to check since I've been running homebrew and all kinds of extra tools on my own laptop.

**Comment by simonw** [comment]
Searching online suggests that `sqlite3` does indeed come by default on all recent versions of macOS.

**Comment by henrykironde** [comment]
Solved in #328
