### ISSUE TITLE
Sharing experiences: How much time is needed for this lesson?

### ISSUE THREAD

**Issue by danmichaelo** [swcarpentry/sql-novice-survey#329]
Not sure if the issue tracker is the right place for this kind of discussion, but it would be interesting to hear from others who teached this lesson: how much time did you schedule for it, and how did it go time-wise? Did you use command line sqlite or DB Browser or both?

We have teached this lesson twice as a full-day course, from 9 to 16, with about one hour for breaks in total, leaving 6 hours to get through the material, focusing only on DB Browser, not command line sqlite. Both times we've ending up rushing the last episodes because of too little time. We did use much more than the allocated time on the first three episodes, however. I'm not sure if that is because the schedule is too tight, or if we progressed too slowly, perhaps a bit of both.

**Comment by henrykironde** [comment]
Thanks @danmichaelo. Personally, I have taught the course and the time was approximately okay. Just for reference, many people have taught the course, but it has always had good and bad timings. I think you do not have to cover everything to the T. Some things are left as one's efforts towards the course. I am happy to hear what other folks have to say.
