### ISSUE TITLE
Updating Prerequisites

### ISSUE THREAD

**Issue by spandalai** [swcarpentry/sql-novice-survey#337]
I want to point to the following two lessons
1) https://swcarpentry.github.io/sql-novice-survey/10-prog/index.html
2) https://swcarpentry.github.io/sql-novice-survey/11-prog-R/index.html

Can we put a few points in the prerequisites that basic knowledge of Python / R would be beneficial? Pointing them to an appropriate Carpentries lesson would also be helpful, in case they would like to lean. 

It is great that this lesson offers learners an option to use SQL from a programming language. Business applications are built on these languages and knowing how to use SQL from these languages can be a huge plus.

Thank you.

**Comment by henrykironde** [comment]
Thank you, Spandalai. Currently, before moving on to SQL, we have either covered Python or R. I think the organization has included that somewhere in the guidelines for using these courses.
