### ISSUE TITLE
Remove DISTINCT from chapter 2

### ISSUE THREAD

**Issue by EspenRosenquist** [swcarpentry/sql-novice-survey#342]
`SELECT DISTINCT quant FROM Survey;`

I would suggest removing the use of the DISTINCT keyword and/or teach the use of GROUP BY instead. 

DISTINCT is not recognized by several SQL engines (GOOGLE BigQuery) and while simple to understand, can lead to all sorts of trouble when building larger sentences. In the order of execution, DISTINCT comes quite far down the chain, while GROUP BY is early. This also means that, when working with big data, you can make savings on data transfer and possibly also computation. Your milage may wary, but should be taken into consideration. You cannot run aggregate functions on DISTINCT results.

I defer all explanations as to the rationale to an excellent thread on [Stackexchange](https://stackoverflow.com/questions/164319/is-there-any-difference-between-group-by-and-distinct), and especially the answer by  Lukas Eder. 

My main argument for removing DISTINCT from the lesson is to make the lesson more focused. Fewer keywords give more time to group by examples.

If not removing DISINCT, put it closer to GROUP BY and illustrate the difference.

**Comment by henrykironde** [comment]
Thank you for your feedback; I agree that `group by` is powerful, but the structure of this lesson aims to provide users with a broad or more generic introduction to database usage (transition from concept to implementation/problem design). Users are expected to do more research on the tools that they want to apply and how to.
