### ISSUE TITLE
Update 2 challenges (or adding null values)?

### ISSUE THREAD

**Issue by xuf12** [swcarpentry/sql-novice-survey#57]
I suggest to update the following 2 challenges:

In the Filter lesson
"Suppose we want to select all sites that lie more than 30 degrees from the poles. Our first query is:
SELECT * FROM Site WHERE (lat > -60) OR (lat < 60);
Explain why this is wrong, and rewrite the query so that it is correct."

The query in question and the correct answer both give the same results because there were only 6 data records, and all of them satisfy both conditions. We may want to use another example or change some values in the data.

In the aggregation lesson:
"The average of a set of values is the sum of the values divided by the number of values. Does this mean that the avg function returns 2.0 or 3.0 when given the values 1.0, null, and 5.0?"

Without a NULL in an integer/real number field, we cannot show an example how SQL takes averages while ignoring NULL. If the data were not real, I'd suggest to replace some of the readings with NULL so that we can demonstrate it.

**Comment by wking** [comment]
On Fri, Apr 03, 2015 at 09:22:53PM -0700, Xu Fei wrote:
> 1. in the Filter lesson
> "Suppose we want to select all sites that lie more than 30 degrees
> from the poles. Our first query is:
> SELECT * FROM Site WHERE (lat > -60) OR (lat < 60);
> Explain why this is wrong, and rewrite the query so that it is correct."
> 
> The query in question and the correct answer both give the same
> results because there were only 6 data records, and all of them
> satisfy both conditions. We may want to use another example or
> change some values in the data.

Aren't there only three sites [1,2]?  Anyway, I agree that this is an
issue.  Maybe we want the cutoff to be 42° from the poles?  Then the
backwards OR version matches all three sites, but only DR-3 has a low
enough latitude to match the real query.  I'd also prefer to use abs()
here [3], but that probably misses the point of thinking about Boolean
logic ;).

> 2. In the aggregation lesson:
> "The average of a set of values is the sum of the values divided by
> the number of values. Does this mean that the avg function returns
> 2.0 or 3.0 when given the values 1.0, null, and 5.0?"
> 
> Without a NULL in an integer/real number field, we cannot show an
> example how SQL takes averages while ignoring NULL. If the data were
> not real, I'd suggest to replace some of the readings with NULL so
> that we can demonstrate it.

I don't think the data are real [4] ;), so replacing at least one
reading with a NULL sounds good to me.

[1]: https://github.com/swcarpentry/sql-novice-survey/blob/a8aa095734a63ff0bdb11ae2d6e9764856e740ee/code/gen-survey-database.sql#L24
[2]: https://github.com/swcarpentry/sql-novice-survey/blob/a8aa095734a63ff0bdb11ae2d6e9764856e740ee/data/site.csv
[3]: https://www.sqlite.org/lang_corefunc.html#abs
[4]: http://en.wikipedia.org/wiki/Miskatonic_University

**Comment by xuf12** [comment]
Thanks Trevor. In this case can I go ahead and submit the following PR?
1. change the cutoff to be 42 as your suggested.
2. change one reading value in the .sql file to null.

**Comment by wking** [comment]
On Sat, Apr 04, 2015 at 02:52:57PM -0700, Xu Fei wrote:
> In this case can I go ahead and submit the following PR?

I'm not a maintainer for this repository, so you might want to wait
until either @acabunoc or @mckays630 chime in.

**Comment by gvwilson** [comment]
Please submit the PR and we'll get someone to review it.
Thanks,
Greg

**Comment by xuf12** [comment]
Just submitted a PR that updated all the lessons and files (hopefully didn't miss anything) that contain query results from the modified SQL script gen-survey-database.sql. Not sure how to update the following 2 files in http://files.software-carpentry.org/
survey.sql
survey.db
