### ISSUE TITLE
wget not in macs

### ISSUE THREAD

**Issue by chendaniely** [swcarpentry/sql-novice-survey#94]
`wget` does not come with macs we should provide a manual download to the survey.db

**Comment by chendaniely** [comment]
does it come with gitbash?

**Comment by r-gaia-cs** [comment]
> `wget` does not come with macs we should provide a manual download to the survey.db

What about `curl`?

> does it come with gitbash?

Can't test it. =(

**Comment by dlebauer** [comment]
If still relevant, I'd like to update the title of the issue to "wget not in macs or Windows" ... 

I just ran the SWC windows installer and when I tried to do the setup, I get 

> wget http://files.software-carpentry.org/survey.db
wget: command not found

`curl` is installed (though FWIW `man` is not)

**Comment by vioan** [comment]
indeed, _curl_ is installed default on OS X, and the equivalent to _wget_ if you want to download a file, is:
`curl "http://www.domain.com/file.jpg" -o "outfile.jpg"`

**Comment by gvwilson** [comment]
We no longer mention `wget` in our lessons.
