### ISSUE TITLE
How should we address readlines not working in older macs in sqlite3?

### ISSUE THREAD

**Issue by chendaniely** [swcarpentry/sql-novice-survey#95]
some of the macs do not have the up arrow to recall history.  How should we address that?  Many instructors have a newer version of sqlite3 and use readline during the lessons and students who do not have it will fall behind

**Comment by jooolia** [comment]
Also an issue for macs today in a session on sqlite3 by @timtomch. Temporary workaround for those mac users was to use it sqlite as a firefox extension.

**Comment by jooolia** [comment]
Update: problem seems to be with version of sqlite3 installed by Anaconda does not have the readline. So mac users were able to run sqlite3 from the command line by running it from /usr/bin/sqlite3

**Comment by jooolia** [comment]
Ok and then we finally saw that we this was already referenced in https://github.com/swcarpentry/workshop-template/pull/230

**Comment by gvwilson** [comment]
@embray any general solution?

**Comment by henrykironde** [comment]
Closing due to new Sqlite platform used and https://github.com/carpentries/workshop-template/pull/230
